### PR TITLE
Remove old PID file

### LINKED ISSUE #61: Remove Opencast PID file once container process is stopped
Sometimes Opencast is terminated and its PID file is not cleaned up. Upon restarting the container Opencast rejects to start. It should be ensured that the PID file is removed once Opencast terminates.

### PR DESCRIPTION
**Pull request by mtneug**
This should fix #61.

### CODE REVIEW

**Comment by mtneug** [comment]
To reproduce the issue one can start an Opencast instance with the docker-compose files and then stop ActiveMQ and MariaDB before Opencast. The stop routine then seems to error leaving the PID file still present.

**Comment by mtneug** [comment]
It turns out that `/opencast/instances/instance.properties` is actually used for looking up the PID. Added that file to the removal list.

**Comment by JanKoppe** [comment]
I'm not really sure if it's a good idea to just remove the PID. Of course, the user should know that only one container should be running at a time, but I can see some weird edge cases happening.

Maybe it would be a better idea to add some command to the start script, which should be manually executed after we display a huge, loud warning when the pid file exists?

**Comment by JanKoppe** [comment]
My concerns have been resolved in a private chat - this scenario should not occur, therefore the approach is safe.

**Pull request merged**
